### ISSUE TITLE
Malformed database schema

### ISSUE THREAD

**Issue by pdehaye** [n8henrie/pycookiecheat#10]
When running the example, I get
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./pycookiecheat/pycookiecheat.py", line 93, in chrome_cookies
    for k, v, ev in conn.execute(sql, (host_key,)):
sqlite3.DatabaseError: malformed database schema (is_transient) - near "where": syntax error`

**Comment by pdehaye** [comment]
Note: my SQLite cookie database does appear to have an index called 'is_transient'

**Comment by n8henrie** [comment]
Can you include some basic information about your setup / environment?

- OS and version
- python version
- sqlite version
- Output of `python -c 'import sqlite3; print(sqlite3.sqlite_version)'` (with whatever python you've installed pycookiecheat)

Looks like it might be [related to an outdated sqlite](http://stackoverflow.com/a/31665275/1588795) (older than 3.8.0 per that thread).

**Comment by n8henrie** [comment]
Closing due to inactivity.

**Comment by pdehaye** [comment]
Sorry, I missed the notification. Yes, it was due to the inappropriate sqlite version, in my case '3.7.13'

**Comment by n8henrie** [comment]
No worries -- thanks for the update.
