### ISSUE TITLE
valueError: Namespace Secret not available

### ISSUE THREAD

**Issue by mahesh3097** [n8henrie/pycookiecheat#25]
I am trying to run a flask application in a docker container . This application uses pycookiecheat to obtain chrome cookies for a login. The app works well when it is on my machine. But i am getting these errors when i am running it on a container

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/flaskapp.py", line 25, in query_submit
    cookies = chrome_cookies(url)
  File "/usr/local/lib/python3.6/dist-packages/pycookiecheat/pycookiecheat.py", line 169, in chrome_cookies
    config = get_linux_config(browser)
  File "/usr/local/lib/python3.6/dist-packages/pycookiecheat/pycookiecheat.py", line 122, in get_linux_config
    gi.require_version('Secret', '1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 127, in require_version
    raise ValueError('Namespace %s not available' % namespace)

**Comment by n8henrie** [comment]
> File "/usr/lib/python3/dist-packages/gi/init.py", line 127, in require_version
raise ValueError('Namespace %s not available' % namespace)

This seems like a problem with the `gi` library, likely with its "sandbox" in a docker container; I'm afraid you'll have to open an issue elsewhere.

I'll be happy to leave the issue open here for a week or so for visibility, to see if anyone else has other ideas, but I think it's likely that the solution may require changes to your docker config and not to pycookiecheat.
