### ISSUE TITLE
GLib.GError: g-io-error-quark: Cannot autolaunch D-Bus without X11 $DISPLAY (0)

### ISSUE THREAD

**Issue by mahesh3097** [n8henrie/pycookiecheat#26]
I am getting this error as I am trying to run my flask app on a server running on Ubuntu 
Not really sure what the cause is or how to resolve it 
Can you help me with this issue?

Traceback (most recent call last):, 
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app, 
    response = self.full_dispatch_request(), 
 File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request, 
   rv = self.handle_user_exception(e), 
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception, 
     reraise(exc_type, exc_value, tb), referer: 
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise, referer:
    raise value, 
 File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request, 
 rv = self.dispatch_request(), 
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request, 
return self.view_functions[rule.endpoint](**req.view_args), 
File "/var/www/FlaskApp/FlaskApp/__init__.py", line 26, in query_submit, 
cookies = chrome_cookies(url), 
File "/usr/local/lib/python3.6/dist-packages/pycookiecheat/pycookiecheat.py", line 169, in chrome_cookies, 
config = get_linux_config(browser),
 File "/usr/local/lib/python3.6/dist-packages/pycookiecheat/pycookiecheat.py", line 128, in get_linux_config,
service = Secret.Service.get_sync(flags), 
GLib.GError: g-io-error-quark: Cannot autolaunch D-Bus without X11 $DISPLAY (0)

**Comment by n8henrie** [comment]
I can't help much, sorry.

As I noted in the related issue (that you commented in), this [is not a problem with pycookiecheat](https://github.com/n8henrie/pycookiecheat/issues/23#issuecomment-469474851) -- if you can run the (non-pycookiecheat) code I included in that comment without errors, please let me know. If you cannot, please work on that issue first. If you find a solution, I'd appreciate if you'd cross-post it here for the benefit of others.

I am considering removing the support for this backend; it seems to be problematic, and people could always just pass in their secret after obtaining it by whatever means.

**Comment by michaellee94** [comment]
I have a fix for this. You need to make sure `DISPLAY` and `DBUS_SESSION_BUS_ADDRESS` are set.

https://comeandtechit.wordpress.com/2018/11/26/glib-error-g-io-error-quark-cannot-autolaunch-d-bus-without-x11-display/
