### ISSUE TITLE
Windows alternative ? 

### ISSUE THREAD

**Issue by fire17** [n8henrie/pycookiecheat#55]
- **Operating system and version**:
Windows 10
- **Python version**:
3.11.5
- **pycookiecheat version**:
latest 0.5.0
## My Issue
Need an aproach that works on windows too

## [WHYT]
I've edited the code to try to open the Cookies file (its in `%LocalAppData%\Google\Chrome\User Data\Default\Network\Cookies` btw)
but im having no luck
current code:
```python
      # ...
      # inside: def chrome_cookies
      # ...
      elif sys.platform == 'win32':
       # Try to get Chrome password from Windows Credential Manager
      try:
        my_pass = keyring.get_password('Chrome Safe Storage', 'Chrome')
        if my_pass is None:
            my_pass = '' 
        else:
            my_pass = my_pass.encode('utf8')
      except keyring.errors.PasswordDeleteError:
        # No saved password, use empty string
        my_pass = ''.encode('utf8')
      iterations = 1
      cookie_file = os.path.expanduser(
        r'%LocalAppData%\Google\Chrome\User Data\Default\Network\Cookies')
      config = {
        'my_pass': b'',  # Default to an empty password
        'iterations': 1,
        'cookie_file': os.path.expandvars(r'%LocalAppData%\Google\Chrome\User Data\Default\Network\Cookies'),
        }
    else:
        raise OSError("This script only works on OSX or Linux.")

    config.update(
        {"init_vector": b" " * 16, "length": 16, "salt": b"saltysalt"}
    )

    if cookie_file:
        cookie_file = str(pathlib.Path(cookie_file).expanduser())
    else:
        cookie_file = str(pathlib.Path(config["cookie_file"]).expanduser())

    if isinstance(password, bytes):
        config["my_pass"] = password
    elif isinstance(password, str):
        config["my_pass"] = password.encode("utf8")
    elif isinstance(config["my_pass"], str):
        config["my_pass"] = config["my_pass"].encode("utf8")

    kdf = PBKDF2HMAC(
        algorithm=SHA1(),
        iterations=config["iterations"],
        length=config["length"],
        salt=config["salt"],
    )
    enc_key = kdf.derive(config["my_pass"])

    try:
        /# Make temp copy to prevent file locking errors  
        #temp_cookie_file = tempfile.NamedTemporaryFile(delete=False)
        #shutil.copyfile(cookie_file, temp_cookie_file.name)
        #conn = sqlite3.connect(temp_cookie_file.name) 
        #conn = sqlite3.connect(cookie_file)
        #conn = sqlite3.connect("file:{}?mode=ro".format(cookie_file), uri=True)
        if not os.path.exists(cookie_file):
            print("Cookie file not found, exiting...")
        else:
            print(" ::: Found FILE! :",cookie_file)
        conn = sqlite3.connect(cookie_file)
        
        #...... rest of program
        

    except sqlite3.OperationalError:
        print("Unable to connect to cookie_file at: {}\n".format(cookie_file))
        raise
```
output:
```
 ::: Found FILE! : C:/Users/User/AppData/Local/Google/Chrome/User Data/Default/Network
Unable to connect to cookie_file at: C:/Users/User/AppData/Local/Google/Chrome/User Data/Default/Network

Traceback (most recent call last):
  File "C:\Users\User\Desktop\transparent-web-app\pycookiecheat\src\pycookiecheat\winrun.py", line 23, in <module>
    cookies = chrome_cookies(url, config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\transparent-web-app\pycookiecheat\src\pycookiecheat\pycookiecheat.py", line 314, in chrome_cookies
    conn = sqlite3.connect(cookie_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file


# am i doing something wrong? `file:{}?mode=ro` isn't working 
```

In General, is anyone familar with an alternative working solution on win?
Thanks a lot, greatly apreciated

**Comment by n8henrie** [comment]
Sorry, I don't have a Windows machine and can't be of much help here.
